import type { SurfSpot } from './weather.types';

export const surfSpots: SurfSpot[] = [
  {
    idealWaveDirection: 180,
    latitude: -34.107,
    longitude: 18.47,
    name: 'Muizenberg',
    offshoreWindDirection: 315,
    waveToleranceDegrees: 75,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 220,
    latitude: -33.9715,
    longitude: 18.3774,
    name: 'Bloubergstrand',
    offshoreWindDirection: 100,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 210,
    latitude: -34.0506,
    longitude: 24.9306,
    name: 'Jeffreys Bay',
    offshoreWindDirection: 330,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 220,
    latitude: -24.836,
    longitude: 15.879,
    name: 'Skeleton Bay',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 55,
    windToleranceDegrees: 45,
  },
  {
    idealWaveDirection: 300,
    latitude: -30.5426,
    longitude: -9.7118,
    name: 'Taghazout',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 75,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 300,
    latitude: 43.665,
    longitude: -1.444,
    name: 'Hossegor',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 75,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 320,
    latitude: 43.407,
    longitude: -2.698,
    name: 'Mundaka',
    offshoreWindDirection: 160,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 300,
    latitude: 39.355,
    longitude: -9.381,
    name: 'Supertubos',
    offshoreWindDirection: 60,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 300,
    latitude: 39.602,
    longitude: -9.07,
    name: 'Nazare',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 80,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 10,
    latitude: 21.664,
    longitude: -158.051,
    name: 'Pipeline',
    offshoreWindDirection: 180,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 180,
    latitude: 21.276,
    longitude: -157.829,
    name: 'Waikiki',
    offshoreWindDirection: 0,
    waveToleranceDegrees: 80,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 220,
    latitude: 33.384,
    longitude: -117.593,
    name: 'Lower Trestles',
    offshoreWindDirection: 45,
    waveToleranceDegrees: 65,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 300,
    latitude: 37.495,
    longitude: -122.496,
    name: 'Mavericks',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 65,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 180,
    latitude: 15.839,
    longitude: -97.041,
    name: 'Puerto Escondido',
    offshoreWindDirection: 0,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 220,
    latitude: -7.702,
    longitude: -79.435,
    name: 'Chicama',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 220,
    latitude: -34.413,
    longitude: -72.035,
    name: 'Punta de Lobos',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 65,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 220,
    latitude: -8.817,
    longitude: 115.087,
    name: 'Uluwatu',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 220,
    latitude: -8.809,
    longitude: 115.102,
    name: 'Padang Padang',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 180,
    latitude: -17.869,
    longitude: 177.187,
    name: 'Cloudbreak',
    offshoreWindDirection: 45,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 180,
    latitude: -17.833,
    longitude: -149.267,
    name: "Teahupo'o",
    offshoreWindDirection: 45,
    waveToleranceDegrees: 65,
    windToleranceDegrees: 50,
  },
  {
    idealWaveDirection: 120,
    latitude: -28.163,
    longitude: 153.546,
    name: 'Snapper Rocks',
    offshoreWindDirection: 270,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 210,
    latitude: -38.37,
    longitude: 144.282,
    name: 'Bells Beach',
    offshoreWindDirection: 30,
    waveToleranceDegrees: 65,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 270,
    latitude: -37.815,
    longitude: 174.822,
    name: 'Manu Bay',
    offshoreWindDirection: 90,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 55,
  },
  {
    idealWaveDirection: 220,
    latitude: 11.469,
    longitude: -86.124,
    name: 'Popoyo',
    offshoreWindDirection: 45,
    waveToleranceDegrees: 70,
    windToleranceDegrees: 60,
  },
  {
    idealWaveDirection: 220,
    latitude: 8.395,
    longitude: -83.135,
    name: 'Pavones',
    offshoreWindDirection: 45,
    waveToleranceDegrees: 60,
    windToleranceDegrees: 55,
  },
];
